// this file is generated by AI tool
import { expressjwt, GetVerificationKey } from 'express-jwt'
import jwksRsa from 'jwks-rsa'
import { auth0Audience, auth0Domain } from '../config'
import { Request } from 'express'

export const checkJwt = expressjwt({
  // Dynamically obtain the JWKS public key
  secret: jwksRsa.expressJwtSecret({
    cache: true,
    rateLimit: true,
    jwksUri: `https://${auth0Domain}/.well-known/jwks.json`,
  }) as GetVerificationKey,
  audience: auth0Audience,
  issuer: `https://${auth0Domain}/`,
  algorithms: ['RS256'],
  requestProperty: 'user',
})

export interface Auth0Request extends Request {
  user?: {
    sub: string       // Auth0 user ID
    [key: string]: unknown
  }
}